### ISSUE TITLE
nbar in steradians

### ISSUE THREAD

**Issue by mehdirezaie** [tanveerkarim/imaging-sys-covariance#3]
Hi @tanveerkarim -- I wonder if you meant to use the mean density in steradians (nbar_sr) in [Line 58](https://github.com/tanveerkarim/imaging-sys-covariance/blob/b173376b024788b5370a249b9221a888c18630da/src/lib.py#L58) and [Line 60](https://github.com/tanveerkarim/imaging-sys-covariance/blob/b173376b024788b5370a249b9221a888c18630da/src/lib.py#L60)

**Comment by tanveerkarim** [comment]
Fixed; changed to nbar_sr
